### ISSUE TITLE
ensure deliverability of logs before server ends by utilizing a flush method & prisma beforeExit hook

### ISSUE THREAD

**Issue by schehata** [axiomhq/prisma-axiom#2]
Currently, prisma-axiom doesn't ensure deliverability of logs. for example if server or request ends before logs are sent to axiom, logs might be lost. A mechanism has to be put in-place to ensure the logs are delivered. 

We can utilize something like:

```typescript
function withAxiom<T>(optionsArg ?: Prisma.Subset<T, Prisma.PrismaClientOptions>) {
  const prisma = new PrismaClient(optionsArg);
  const { middleware, flush } = logWithAxiom();
  prisma.$use(middleware);
  prisma.$on('beforeExit', flush);
  return prisma;
}
```

**Comment by bahlo** [comment]
This is done 🙌
